//go:build integration

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"vox/internal/hub"
	"vox/tests/utils/helpers"
)

func TestNewHubHandler_HubAlreadyExists(t *testing.T) {
	mgr := hub.NewManager()
	existingID := mgr.New() // seed a real hub

	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(existingID))

	assert.Equal(t, http.StatusConflict, w.Code)
}

func TestNewHubHandler_HappyPath_StatusCreated(t *testing.T) {
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(uuid.New().String()))

	assert.Equal(t, http.StatusCreated, w.Code)
}

func TestNewHubHandler_HappyPath_ResponseBodyIsValidJSON(t *testing.T) {
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(uuid.New().String()))

	require.Equal(t, http.StatusCreated, w.Code)
	assert.True(t, json.Valid(w.Body.Bytes()), "response body must be valid JSON")
}

func TestNewHubHandler_HappyPath_ResponseContainsNonEmptyHubID(t *testing.T) {
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(uuid.New().String()))

	require.Equal(t, http.StatusCreated, w.Code)

	var body map[string]string
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))
	assert.NotEmpty(t, body["hub_id"])
}

func TestNewHubHandler_HappyPath_ReturnsManagerGeneratedID_NotURLParam(t *testing.T) {
	// The handler reassigns hubID = h.Manager.New(), so the response hub_id
	// must be what the manager generated (a UUID), not the caller's URL segment.
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	callerSuppliedID := uuid.New().String()
	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(callerSuppliedID))

	require.Equal(t, http.StatusCreated, w.Code)

	var body map[string]string
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))

	// The returned ID must be a valid UUID generated by the manager.
	_, err := uuid.Parse(body["hub_id"])
	assert.NoError(t, err, "hub_id in response must be a valid UUID from the manager")

	// And it must differ from the caller-supplied URL param.
	assert.NotEqual(t, callerSuppliedID, body["hub_id"])
}

func TestNewHubHandler_HappyPath_HubIsRegisteredInManager(t *testing.T) {
	// After a successful creation, the hub must actually exist in the manager.
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(uuid.New().String()))

	require.Equal(t, http.StatusCreated, w.Code)

	var body map[string]string
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))

	_, ok := mgr.Get(body["hub_id"])
	assert.True(t, ok, "newly created hub must be retrievable from the manager")
}

func TestNewHubHandler_HappyPath_ContentTypeIsJSON(t *testing.T) {
	mgr := hub.NewManager()
	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(uuid.New().String()))

	require.Equal(t, http.StatusCreated, w.Code)
	assert.Contains(t, w.Header().Get("Content-Type"), "application/json")
}

func TestNewHubHandler_ConflictDoesNotCreateAdditionalHub(t *testing.T) {
	mgr := hub.NewManager()
	existingID := mgr.New() // one hub in the manager

	api := &hub.HubAPI{MGR: mgr}
	r := helpers.NewHubRouter(t, api)

	w := httptest.NewRecorder()
	r.ServeHTTP(w, helpers.NewHubRequest(existingID))

	require.Equal(t, http.StatusConflict, w.Code)

	// Manager must still contain exactly one hub — the original.
	_, ok := mgr.Get(existingID)
	assert.True(t, ok, "original hub must still exist after conflict")
}
